repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: local
    hooks:
      - id: typescript-lint
        name: typescript lint
        entry: npm run lint
        language: system
        pass_filenames: false
